import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json({ limit: '10mb' }));

// Gemini Setup
const genAI = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY || "",
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

// Mock Database (In-memory for demo, should be Firestore/DB in prod)
const db = {
  users: [
    { id: 'user_123', name: '张三', enterprise: 'Perfume Co.', integral: 100, role: 1 }
  ],
  tools: [
    { id: 'tool_perfume', name: '香水 AI 全案设计', integral: 10, status: 'active' }
  ],
  userImages: [] as any[],
  pendingUploads: new Map<string, any>()
};

// --- Gemini API Routes ---

app.post("/api/ai/analyze", async (req, res) => {
  try {
    const { image } = req.body;
    if (!image) return res.status(400).json({ error: "Image required" });

    const base64Data = image.split(",")[1] || image;

    const prompt = `
      Analyze this perfume bottle image and provide:
      1. A short, attractive title (in Chinese).
      2. 1-3 key selling points (in Chinese).
      3. A short bottom info line (in Chinese).
      4. A suitable dark/luxury text color (Hex code).
      Return strictly as JSON: { "title": "...", "sellingPoints": ["...", "..."], "bottomInfo": "...", "textColor": "..." }
    `;

    const response = await genAI.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: {
        parts: [
          { inlineData: { data: base64Data, mimeType: "image/png" } },
          { text: prompt }
        ]
      }
    });

    const responseText = response.text;
    const jsonMatch = responseText?.match(/\{[\s\S]*\}/);
    if (!jsonMatch) throw new Error("Invalid AI response: " + responseText);
    
    res.json(JSON.parse(jsonMatch[0]));
  } catch (error: any) {
    console.error("AI Analysis error:", error);
    res.status(500).json({ error: error.message });
  }
});

app.post("/api/ai/generate", async (req, res) => {
  try {
    const { image, stylePrompt, aspectRatio, quality, perspectivePrompt } = req.body;
    if (!image) return res.status(400).json({ error: "Image required" });

    const base64Data = image.split(",")[1] || image;

    const finalPrompt = `
      Create a high-end commercial product photography background for the product in the provided image.
      - Product: Maintain EXACT shape/material of the reference bottle.
      - Perspective: ${perspectivePrompt}.
      - Style: ${stylePrompt}.
      - Background: Consistent studio setup, high-end bokeh, luxurious lighting.
      - REPEAT: Absolute focus on the product. No extra digital text or graphics.
      - Quality: Professional catalog photography.
    `;

    const response = await genAI.models.generateContent({
      model: 'gemini-3.1-flash-image-preview',
      contents: {
        parts: [
          { inlineData: { data: base64Data, mimeType: "image/png" } },
          { text: finalPrompt }
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: (aspectRatio || "1:1") as any,
          imageSize: (quality || "1K") as any
        }
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return res.json({ 
          success: true, 
          image: `data:image/png;base64,${part.inlineData.data}` 
        });
      }
    }

    throw new Error("No image generated by Gemini");
  } catch (error: any) {
    console.error("AI Generation error:", error);
    res.status(500).json({ error: error.message });
  }
});

// --- SaaS Integration APIs (as per doc) ---

// A. Launch
app.post("/api/tool/launch", (req, res) => {
  const { userId, toolId } = req.body;
  const user = db.users.find(u => u.id === userId) || db.users[0];
  const tool = db.tools.find(t => t.id === toolId) || db.tools[0];
  
  res.json({
    success: true,
    data: { user, tool }
  });
});

// B. Verify
app.post("/api/tool/verify", (req, res) => {
  const { userId, toolId } = req.body;
  const user = db.users.find(u => u.id === userId) || db.users[0];
  const tool = db.tools.find(t => t.id === toolId) || db.tools[0];

  if (user.integral < tool.integral) {
    return res.status(400).json({
      success: false,
      message: `积分不足，还差 ${tool.integral - user.integral} 积分`
    });
  }

  res.json({
    success: true,
    data: {
      currentIntegral: user.integral,
      requiredIntegral: tool.integral
    }
  });
});

// C. Consume
app.post("/api/tool/consume", (req, res) => {
  const { userId, toolId } = req.body;
  const user = db.users.find(u => u.id === userId);
  const tool = db.tools.find(t => t.id === toolId);

  if (!user || !tool) return res.status(404).json({ success: false, message: "User or Tool not found" });

  user.integral -= tool.integral;
  
  // Set pending flag for upload
  const pendingKey = `${userId}:${toolId}`;
  db.pendingUploads.set(pendingKey, { timestamp: Date.now() });

  res.json({
    success: true,
    message: "积分扣除成功",
    data: {
      currentIntegral: user.integral,
      consumedIntegral: tool.integral,
      toolId: tool.id
    }
  });
});

// D. Direct Token (OSS Upload)
app.post("/api/upload/direct-token", (req, res) => {
  const { userId, toolId, source, mimeType, fileName, fileSize } = req.body;
  
  const pendingKey = `${userId}:${toolId}`;
  if (!db.pendingUploads.has(pendingKey)) {
    return res.status(403).json({ success: false, message: "No pending consumption found" });
  }

  const objectKey = `result/${Date.now()}_${fileName || 'image.png'}`;
  
  // In a real Aliyun OSS setup, we'd generate a signed PUT URL here.
  // For this demo, we'll return a mock URL that points to our own server.
  const uploadUrl = `http://localhost:3000/api/mock-oss-upload?key=${objectKey}`;

  res.json({
    success: true,
    source: "result",
    method: "PUT",
    objectKey,
    fileName: objectKey,
    uploadUrl,
    ossUploadUrl: uploadUrl,
    uploadStrategy: "oss-direct",
    headers: {
      "Content-Type": mimeType || "image/png"
    },
    commitUrl: "/api/upload/commit",
    expiresIn: 600
  });
});

// Mock OSS Upload Endpoint
app.put("/api/mock-oss-upload", (req, res) => {
  const key = req.query.key as string;
  console.log(`Mock OSS: Uploading ${key}...`);
  // In reality, save the stream to a bucket or local file
  res.status(200).send();
});

// E. Commit
app.post("/api/upload/commit", (req, res) => {
  const { userId, toolId, source, objectKey, fileSize } = req.body;
  
  const pendingKey = `${userId}:${toolId}`;
  // In prod, check if consumption exists and objectKey is valid
  
  const recordId = `img_${Math.random().toString(36).substr(2, 9)}`;
  const publicUrl = `https://picsum.photos/seed/${recordId}/1024/1024`; // Mock URL

  const newImage = {
    id: recordId,
    recordId,
    userId,
    userName: db.users.find(u => u.id === userId)?.name || "Unknown",
    url: publicUrl,
    fileName: objectKey,
    fileSize: fileSize || 0,
    createdAt: new Date().toISOString()
  };

  db.userImages.push(newImage);
  db.pendingUploads.delete(pendingKey);

  res.json({
    success: true,
    source: "result",
    savedToRecords: true,
    recordId,
    url: publicUrl,
    fileName: objectKey,
    image: newImage
  });
});

// F. Get User Images
app.get("/api/upload/image", (req, res) => {
  const { userId, role } = req.query;
  
  let images = db.userImages;
  if (role !== '2') {
    images = images.filter(img => img.userId === userId);
  }

  res.json({
    success: true,
    data: images,
    total: images.length
  });
});

// G. Delete Image
app.delete("/api/upload/image", (req, res) => {
  const { id, userId, role } = req.body;
  
  const index = db.userImages.findIndex(img => img.id === id);
  if (index === -1) return res.status(404).json({ success: false, message: "Image not found" });

  if (role !== '2' && db.userImages[index].userId !== userId) {
    return res.status(403).json({ success: false, message: "Forbidden" });
  }

  db.userImages.splice(index, 1);
  res.json({ success: true, message: "Deleted successfully" });
});

// --- Server Setup ---

async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
