import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json({ limit: '10mb' }));

// Gemini Setup
const genAI = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY || "",
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

// Mock Database (In-memory for demo, should be Firestore/DB in prod)
const db = {
  users: [
    { id: 'user_123', name: '张三', enterprise: 'Perfume Co.', integral: 100, role: 1 }
  ],
  tools: [
    { id: 'tool_perfume', name: '香水 AI 全案设计', integral: 10, status: 'active' }
  ],
  userImages: [] as any[],
  pendingUploads: new Map<string, any>()
};

// --- Gemini API Routes ---

app.post("/api/ai/analyze", async (req, res) => {
  try {
    const { image } = req.body;
    if (!image) return res.status(400).json({ error: "Image required" });

    const base64Data = image.split(",")[1] || image;

    const prompt = `
      Analyze this perfume bottle image and provide:
      1. A short, attractive title (in Chinese).
      2. 1-3 key selling points (in Chinese).
      3. A short bottom info line (in Chinese).
      4. A suitable dark/luxury text color (Hex code).
      Return strictly as JSON: { "title": "...", "sellingPoints": ["...", "..."], "bottomInfo": "...", "textColor": "..." }
    `;

    const response = await genAI.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: {
        parts: [
          { inlineData: { data: base64Data, mimeType: "image/png" } },
          { text: prompt }
        ]
      }
    });

    const responseText = response.text;
    const jsonMatch = responseText?.match(/\{[\s\S]*\}/);
    if (!jsonMatch) throw new Error("Invalid AI response: " + responseText);
    
    res.json(JSON.parse(jsonMatch[0]));
  } catch (error: any) {
    console.error("AI Analysis error:", error);
    res.status(500).json({ error: error.message });
  }
});

app.post("/api/ai/generate", async (req, res) => {
  try {
    const { image, stylePrompt, aspectRatio, quality, perspectivePrompt } = req.body;
    if (!image) return res.status(400).json({ error: "Image required" });

    const base64Data = image.split(",")[1] || image;

    const finalPrompt = `
      Create a high-end commercial product photography background for the product in the provided image.
      - Product: Maintain EXACT shape/material of the reference bottle.
      - Perspective: ${perspectivePrompt}.
      - Style: ${stylePrompt}.
      - Background: Consistent studio setup, high-end bokeh, luxurious lighting.
      - REPEAT: Absolute focus on the product. No extra digital text or graphics.
      - Quality: Professional catalog photography.
    `;

    const response = await genAI.models.generateContent({
      model: 'gemini-3.1-flash-image-preview',
      contents: {
        parts: [
          { inlineData: { data: base64Data, mimeType: "image/png" } },
          { text: finalPrompt }
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: (aspectRatio || "1:1") as any,
          imageSize: (quality || "1K") as any
        }
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return res.json({ 
          success: true, 
          image: `data:image/png;base64,${part.inlineData.data}` 
        });
      }
    }

    throw new Error("No image generated by Gemini");
  } catch (error: any) {
    console.error("AI Generation error:", error);
    res.status(500).json({ error: error.message });
  }
});

// --- SaaS Integration APIs (Proxied to aibigtree.com) ---
const SAAS_BASE_URL = "http://aibigtree.com";

const proxyToSaas = async (req: express.Request, res: express.Response) => {
  const targetUrl = `${SAAS_BASE_URL}${req.path}${req.url.includes('?') ? req.url.substring(req.url.indexOf('?')) : ''}`;
  console.log(`Proxying SaaS request to: ${targetUrl} (${req.method})`);

  try {
    const saasRes = await fetch(targetUrl, {
      method: req.method,
      headers: {
        'Content-Type': 'application/json',
        ...(req.headers.authorization ? { 'Authorization': req.headers.authorization as string } : {}),
      },
      body: req.method !== 'GET' && req.method !== 'HEAD' && req.method !== 'OPTIONS' ? JSON.stringify(req.body) : undefined,
    });

    const contentType = saasRes.headers.get('content-type');
    if (contentType && contentType.includes('application/json')) {
      const data = await saasRes.json();
      res.status(saasRes.status).json(data);
    } else {
      const text = await saasRes.text();
      res.status(saasRes.status).send(text);
    }
  } catch (err: any) {
    console.error("SaaS Proxy Error:", err);
    res.status(500).json({ error: err.message });
  }
};

app.post("/api/tool/launch", (req, res) => {
  const { userId, toolId } = req.body;
  const user = db.users.find(u => u.id === userId) || db.users[0];
  const tool = db.tools.find(t => t.id === toolId) || db.tools[0];

  res.json({
    success: true,
    data: {
      user,
      tool
    }
  });
});

app.post("/api/tool/verify", (req, res) => {
  const { userId, toolId } = req.body;
  const user = db.users.find(u => u.id === userId) || db.users[0];
  const tool = db.tools.find(t => t.id === toolId) || db.tools[0];

  if (user.integral < tool.integral) {
    return res.status(200).json({
      success: false,
      message: `积分不足，还差 ${tool.integral - user.integral} 积分`
    });
  }

  res.json({
    success: true,
    data: {
      currentIntegral: user.integral,
      requiredIntegral: tool.integral
    }
  });
});

app.post("/api/tool/consume", (req, res) => {
  const { userId, toolId } = req.body;
  const user = db.users.find(u => u.id === userId) || db.users[0];
  const tool = db.tools.find(t => t.id === toolId) || db.tools[0];

  if (user.integral < tool.integral) {
    return res.status(200).json({
      success: false,
      message: "积分扣除失败: 积分不足"
    });
  }

  user.integral -= tool.integral;
  
  // Create short-duration flag for result image upload
  db.pendingUploads.set(`${userId || user.id}_${toolId || tool.id}`, {
    timestamp: Date.now(),
    expiresAt: Date.now() + 5 * 60 * 1000 // 5 mins
  });

  res.json({
    success: true,
    message: "积分扣除成功",
    data: {
      currentIntegral: user.integral,
      consumedIntegral: tool.integral,
      toolId: toolId || tool.id
    }
  });
});

app.post("/api/upload/direct-token", (req, res) => {
  const { userId, toolId, fileName } = req.body;
  
  // Verify token
  const flag = db.pendingUploads.get(`${userId}_${toolId}`);
  if (!flag || flag.expiresAt < Date.now()) {
    return res.status(403).json({ success: false, error: "Missing or expired upload token" });
  }

  // Remove flag (one-time use for simplicity, or keep if multiple uploads?)
  // Let's keep it until it expires as we might upload multiple images.
  
  const objectKey = `uploads/${userId}_${Date.now()}_${fileName}`;
  
  res.json({
    success: true,
    uploadUrl: `/api/upload/mock-put?key=${encodeURIComponent(objectKey)}`,
    method: "POST",
    objectKey: objectKey,
    headers: {}
  });
});

app.post("/api/upload/mock-put", express.raw({ type: () => true, limit: '10mb' }), (req, res) => {
  // Store the raw body as base64 in our local mock db so we can serve it later
  const key = req.query.key as string;
  if (!key) return res.status(400).send("Missing key");

  // Since it's raw binary data, we convert it to base64
  const base64Data = req.body.toString('base64');
  let mimeType = req.headers['content-type'] || 'image/png';
  
  // Save temp
  (db as any)[`temp_${key}`] = `data:${mimeType};base64,${base64Data}`;

  res.status(200).send("OK");
});

app.post("/api/upload/commit", (req, res) => {
  const { userId, toolId, objectKey } = req.body;
  
  const tempImage = (db as any)[`temp_${objectKey}`];
  if (!tempImage) {
    return res.status(400).json({ success: false, error: "Image not uploaded" });
  }

  const newImage = {
    id: `img_${Date.now()}`,
    url: tempImage,
    fileName: objectKey.split('/').pop() || 'image.png',
    createdAt: Date.now(),
    toolId: toolId // Record which tool generated this
  };

  db.userImages.unshift(newImage);

  res.json({
    success: true,
    savedToRecords: true,
    image: newImage
  });
});

app.get("/api/upload/image", (req, res) => {
  const { userId, toolId } = req.query;
  let filtered = db.userImages;
  
  if (toolId) {
    filtered = filtered.filter(img => img.toolId === toolId);
  }
  
  res.json({
    success: true,
    data: filtered
  });
});

app.delete("/api/upload/image", (req, res) => {
  const { id } = req.body;
  db.userImages = db.userImages.filter(img => img.id !== id);
  res.json({ success: true, message: "Deleted" });
});

// app.all("/api/tool/*", proxyToSaas);
// app.all("/api/upload/*", proxyToSaas);

// --- Server Setup ---

async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
