import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json({ limit: '10mb' }));

// Gemini Setup
const genAI = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY || "",
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

// Mock Database (In-memory for demo, should be Firestore/DB in prod)
const db = {
  users: [
    { id: 'user_123', name: '张三', enterprise: 'Perfume Co.', integral: 100, role: 1 }
  ],
  tools: [
    { id: 'tool_perfume', name: '香水 AI 全案设计', integral: 10, status: 'active' }
  ],
  userImages: [] as any[],
  pendingUploads: new Map<string, any>()
};

// --- Gemini API Routes ---

app.post("/api/ai/analyze", async (req, res) => {
  try {
    const { image } = req.body;
    if (!image) return res.status(400).json({ error: "Image required" });

    const base64Data = image.split(",")[1] || image;

    const prompt = `
      Analyze this perfume bottle image and provide:
      1. A short, attractive title (in Chinese).
      2. 1-3 key selling points (in Chinese).
      3. A short bottom info line (in Chinese).
      4. A suitable dark/luxury text color (Hex code).
      Return strictly as JSON: { "title": "...", "sellingPoints": ["...", "..."], "bottomInfo": "...", "textColor": "..." }
    `;

    const response = await genAI.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: {
        parts: [
          { inlineData: { data: base64Data, mimeType: "image/png" } },
          { text: prompt }
        ]
      }
    });

    const responseText = response.text;
    const jsonMatch = responseText?.match(/\{[\s\S]*\}/);
    if (!jsonMatch) throw new Error("Invalid AI response: " + responseText);
    
    res.json(JSON.parse(jsonMatch[0]));
  } catch (error: any) {
    console.error("AI Analysis error:", error);
    res.status(500).json({ error: error.message });
  }
});

app.post("/api/ai/generate", async (req, res) => {
  try {
    const { image, stylePrompt, aspectRatio, quality, perspectivePrompt } = req.body;
    if (!image) return res.status(400).json({ error: "Image required" });

    const base64Data = image.split(",")[1] || image;

    const finalPrompt = `
      Create a high-end commercial product photography background for the product in the provided image.
      - Product: Maintain EXACT shape/material of the reference bottle.
      - Perspective: ${perspectivePrompt}.
      - Style: ${stylePrompt}.
      - Background: Consistent studio setup, high-end bokeh, luxurious lighting.
      - REPEAT: Absolute focus on the product. No extra digital text or graphics.
      - Quality: Professional catalog photography.
    `;

    const response = await genAI.models.generateContent({
      model: 'gemini-3.1-flash-image-preview',
      contents: {
        parts: [
          { inlineData: { data: base64Data, mimeType: "image/png" } },
          { text: finalPrompt }
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: (aspectRatio || "1:1") as any,
          imageSize: (quality || "1K") as any
        }
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return res.json({ 
          success: true, 
          image: `data:image/png;base64,${part.inlineData.data}` 
        });
      }
    }

    throw new Error("No image generated by Gemini");
  } catch (error: any) {
    console.error("AI Generation error:", error);
    res.status(500).json({ error: error.message });
  }
});

// --- SaaS Integration APIs (Proxied to aibigtree.com) ---

const SAAS_BASE_URL = "http://aibigtree.com";

app.all(["/api/tool/*", "/api/upload/*"], async (req, res) => {
  const targetUrl = `${SAAS_BASE_URL}${req.path}${req.url.includes('?') ? req.url.substring(req.url.indexOf('?')) : ''}`;
  console.log(`Proxying SaaS request to: ${targetUrl}`);

  try {
    const saasRes = await fetch(targetUrl, {
      method: req.method,
      headers: {
        'Content-Type': 'application/json',
        ...(req.headers.authorization ? { 'Authorization': req.headers.authorization } : {}),
      },
      body: req.method !== 'GET' && req.method !== 'HEAD' && req.method !== 'OPTIONS' ? JSON.stringify(req.body) : undefined,
    });

    const contentType = saasRes.headers.get('content-type');
    if (contentType && contentType.includes('application/json')) {
      const data = await saasRes.json();
      res.status(saasRes.status).json(data);
    } else {
      const text = await saasRes.text();
      res.status(saasRes.status).send(text);
    }
  } catch (err: any) {
    console.error("SaaS Proxy Error:", err);
    res.status(500).json({ error: err.message });
  }
});

// --- Server Setup ---

async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
